name: MyTemplateiOSApp
options:
  xcodeVersion: 15.1
  deploymentTarget:
    iOS: 17.0

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.hiroakiapp.MyTemplateiOSApp
    DEVELOPMENT_TEAM: Saito Hiroaki (Personal Team)
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic

targets:
  MyTemplateiOSApp:
    type: application
    platform: iOS
    sources:
      - path: MyTemplateiOSApp
    settings:
      base:
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_ASSET_PATHS: "\"MyTemplateiOSApp/Preview Content\""
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: MyTemplateiOSApp/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
    dependencies:
      - target: MyTemplateiOSApp
    postBuildScripts:
      - name: Run SwiftLint
        path: /bin/sh
        script: |-
          if [[ "$(uname -m)" == arm64 ]]; then
            export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
  MyTemplateiOSAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - MyTemplateiOSAppTests
    dependencies:
      - target: MyTemplateiOSApp
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
  MyTemplateiOSAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - MyTemplateiOSAppUITests
    dependencies:
      - target: MyTemplateiOSApp
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
