name: MyTemplateiOSApp
options:
  xcodeVersion: "15.2"
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    DEVELOPMENT_TEAM: SAITO HIROAKI
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic

targets:
  MyTemplateiOSApp:
    type: application
    platform: iOS
    sources:
      - path: MyTemplateiOSApp
    options:
        bundleIdPrefix: com.mothule
    settings:
      base:
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_ASSET_PATHS: "\"MyTemplateiOSApp/Preview Content\""
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      # 生成先のPathを指定する
      path: MyTemplateiOSApp/Info.plist
      # 各種設定は基本的にXcode 13.1のテンプレートから作成したものとあわせる
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
    dependencies:
      - target: MyTemplateiOSApp
    postBuildScripts:
      - name: Run SwiftLint
        path: /bin/sh
        script: |-
          if [[ "$(uname -m)" == arm64 ]]; then
            export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
  MyTemplateiOSAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - MyTemplateiOSAppTests
    dependencies:
      - target: MyTemplateiOSApp
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
  MyTemplateiOSAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - MyTemplateiOSAppUITests
    dependencies:
      - target: MyTemplateiOSApp
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES

schemes:
  MyTemplateiOSApp:
    build:
      targets:
        MyTemplateiOSApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug
