name: MyTemplateiOSApp
options:
  xcodeVersion: "15.2"
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: 5.0

targets:
  MyTemplateiOSApp:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: $TARGET_NAME
        PRODUCT_BUNDLE_IDENTIFIER: com.hiroakiapp.MyTemplateiOSApp
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: true
        GENERATE_INFOPLIST_FILE: true
        ENABLE_USER_SCRIPT_SANDBOXING: false
        INFOPLIST_KEY_CFBundleDisplayName: ${PRODUCT_NAME}
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen.storyboard
        INFOPLIST_KEY_UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    sources:
      - path: MyTemplateiOSApp
    dependencies:
      - package: MyTemplateiOSApp
        products:
          - App
    postBuildScripts:
      - name: Run SwiftLint
        path: /bin/sh
        script: |-
          if [[ "$(uname -m)" == arm64 ]]; then
            export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
  MyTemplateiOSAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - MyTemplateiOSAppTests
    dependencies:
      - target: MyTemplateiOSApp
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
  MyTemplateiOSAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - MyTemplateiOSAppUITests
    dependencies:
      - target: MyTemplateiOSApp
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES

schemes:
  MyTemplateiOSApp:
    build:
      targets:
        MyTemplateiOSApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug
