# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do |lane|
    ensure_xcode_version
  end

  lane :test do |option|
    scan(
      scheme: "MyTemplateiOSApp",
      device: "iPhone 15",
      configuration: "Debug",
      clean: true,
      skip_build: true
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end

end
