name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.1.app

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-13
    env:
      MINT_PATH: mint/lib
      MINT_LINK_PATH: mint/bin
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: sudo xcode-select -s '/Applications/Xcode_15.1.app/Contents/Developer'
      - name: Cache Gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Bundled Gems
        run: |
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3
      - name: Install Mint
        run: brew install mint
      # Mintで管理しているライブラリのキャッシュ
      - name: Cache Mint packages
        uses: actions/cache@v4
        with:
          path: mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-
      - name: Build Env Setting
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool true
      - name: Cache Mint packages
        uses: actions/cache@v4
        with:
          path: mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-
      - name: Bundle FastLane Test
        run: bundle exec fastlane test
